version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ticket-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ticket_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:alpine
    container_name: ticket-redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: ticket-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ticket_db?useSSL=false&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}